### ISSUE TITLE
false negative

### ISSUE THREAD

**Issue by hiburn8** [sideeffect42/RootPipeTester#1]
says it couldn't write the files but it managed to ok. (tested on 10.10.2)

**Comment by sideeffect42** [comment]
I've seen the same error on Mavericks. Will look into it.

**Comment by sideeffect42** [comment]
@hiburn8: Does @beatjunky99's commit fix your issues on 10.10.2, too?

You may want to try Release [v1.0.2b1](https://github.com/sideeffect42/RootPipeTester/releases/tag/v1.0.2b1)

**Comment by sebikeller** [comment]
Can't tell if it fixes on 10.10.2, since i don't have a 10.10 installation < 10.10.3 ready to test.
But i think it will also fix them.

**Comment by hiburn8** [comment]
Sorry for slow reply. I patched my system but i tested this on a friends machine and the commit seems to have fixed the false negative on 10.10.2 :)

**Comment by sideeffect42** [comment]
Fixed: Check release [1.0.2](https://github.com/sideeffect42/RootPipeTester/releases/tag/v1.0.2)
